repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix, src]
      - id: ruff-format
        types_or: [python, pyi]
        args: [src]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: '^labs/.*'
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
        types: [yaml]
      - id: check-toml
        types: [toml]
      - id: end-of-file-fixer
        types: [yaml, python, markdown, toml, text]
      - id: trailing-whitespace
        types: [yaml, python, markdown, toml, text]
      - id: debug-statements
        types: [python]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
      - id: nbstripout
        args: ['--drop-empty-cells', '--keep-output', '--extra-keys=metadata.celltoolbar cell.metadata.heading_collapsed metadata.kernelspec metadata.language_info.version']
